### ISSUE TITLE
Atari Lynx Core

### ISSUE THREAD

**Issue by Brianvgplayer** [MikeS11/YC_Builds-MiSTer#3]
This core supports 15kHz TVs/Monitors, but hasn't been updated for Y/C.

**Comment by MikeS11** [comment]
The main mister core now has the new yc framework :). I'm slowly removing the YC cores when they are updated on the mister-devel repo

**Comment by Brianvgplayer** [comment]
My concern is that Atari Lynx never had a Y/C core, even before the cores being added to the new framework.

**Comment by MikeS11** [comment]
If there is any dot crawl, Ill be adding the tuned values to the yc.txt file to clean things up. The framework has the exact same module used in the yc cores.

**Comment by Brianvgplayer** [comment]
I didn't know where to post, so I was asking about Y/C support for the Atari Lynx. I understand that cores are being added to the repro, but the Atari Lynx was never playable on mister with direct Y/C and I was wondering if it was possible for Y/C to be added for Lynx (which would be in the main repro now).

**Comment by MikeS11** [comment]
I actually skipped it because I didn't see the 240p mode, I'll make sure it
gets added.

**Comment by MikeS11** [comment]
I've added a test build on discord if you want to try it out
